name: Create release tag
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version to create/release (for example 1.0.0)'
        required: true

env:
  # Personal access token is needed so that this action can create other action (release)
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ inputs.release-version }}
      DEV_VERSION: 1.0-SNAPSHOT
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Init Git info
        run: |
          git config --global user.email "actions@workflow.github.com"
          git config --global user.name "GitHub Actions"
      - name: Update versions
        run: |
          mvn --no-transfer-progress versions:set -DnewVersion=${RELEASE_VERSION} -DoldVersion=* -DgroupId=* -DartifactId=* -DgenerateBackupPoms=false
      - name: Create tag
        run: |
          git add -A
          git commit -m "[Release] Release ${RELEASE_VERSION}"
          git tag v${RELEASE_VERSION}
      - name: Revert versions
        run: |
          mvn --no-transfer-progress versions:set -DnewVersion=${DEV_VERSION} -DoldVersion=* -DgroupId=* -DartifactId=* -DgenerateBackupPoms=false
      - name: Push changes
        run: |
          git add -A
          git commit -m "[Release] Back to ${DEV_VERSION}"
          git push origin main
          git push origin v${RELEASE_VERSION}

