name: Dependencies diff
on: pull_request

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  diff:
    runs-on: ubuntu-latest
    name: Dependencies diff
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch the whole history to have all released tags available
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Create diff
        run: |
          # resolve all dependencies from the HEAD of this PR
          mvn compile dependency:resolve -DappendOutput=true -DoutputFile=head.log
          git checkout main
          # resolve all dependencies from the HEAD of this PR
          mvn compile dependency:resolve -DappendOutput=true -DoutputFile=main.log
          printf "Dependencies diff:\n\`\`\`\n%s\n\`\`\`" "$(diff head.log main.log)" > diff.txt
      - name: Add comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: diff.txt

