name: Sync BOM
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-bom:
    name: Sync BOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build BOM
        run: |
          mvn --no-transfer-progress --activate-profiles update-bom clean install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: 'bom/pom.xml'
          commit-message: '[BOM] Sync BOM'
          branch: 'action-sync-bom'
          delete-branch: true
          title: 'Sync BOM'
          assignees: 'avano'

